name: update-adhesions-status
on:
  schedule:
    - cron: '0 10 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route every day at 10AM
        run: |
          curl --request POST --url '${{ secrets.SITE_URL }}/api/adhesion/update-adhesions-status' \
          --header 'Authorization: Bearer ${{ secrets.API_KEY }}'
